### PR TITLE
ADD turbolinks support

### PR DESCRIPTION
**Pull request by achmiral**
- Add turbolinks 5.2.0
- Fix turbolinks browsersyc integration using snippetOptions
- Change browsersync port to 8080
- Update stilsa.js, scripts.js and custom.js
- Add script tag for tubolinks on master layout
- Generate new pages folder

### CODE REVIEW

**Comment by nauvalazhar** [comment]
Hi, thank you for your contribution. I'll try it first, but, please remove `type="text/javascript"` on your `<script>` tag.

Thank you

**Comment by nauvalazhar** [comment]
Also, place the `<script>` tag of Turbolink before the `</ body>` tag.

**Comment by nauvalazhar** [comment]
I found a bug; when you go to page "A" and go to page "B", then go to page "A" again, then the event that was initialized will be fire 2 times or more. This is because Turbolink initializes several times depending on the page visited.

**Comment by SunDi3yansyah** [comment]
> I found a bug; when you go to page "A" and go to page "B", then go to page "A" again, then the event that was initialized will be fire 2 times or more. This is because Turbolink initializes several times depending on the page visited.

seems to have to add something like this:
```
data-turbolinks-track="reload" data-turbolinks-eval="false"
```
in the script tag

**Pull request closed without merging**
