### PR TITLE
Replace nicescroll plugin to native scrollbars

### PR DESCRIPTION
**Pull request by tomferreira**
Remove all references to nicescroll plugin and use native scrollbars to simplify and reduce asset size

https://github.com/stisla/stisla/issues/13

Comparison
comparison

### CODE REVIEW

**Comment by polynar** [comment]
Please update the assets folder too with compiled code.

**Comment by polynar** [comment]
After I click to collapse sidebar and back to the normal sidebar, the sidebar scroll doesn't work.

**Comment by tomferreira** [comment]
> Please update the assets folder too with compiled code.

I also synced older changes to the asset folder

**Comment by nauvalazhar** [comment]
Hi, thank you for your contribution. How does it look on Windows?

**Comment by tomferreira** [comment]
> Hi, thank you for your contribution. How does it look on Windows?

Hi, 
The negative point is that in the current version of Microsoft Edge there is no solution yet, but it works perfectly with the new version based on Chromium.

**Comment by nauvalazhar** [comment]
Ok, can you send me a screenshot?

**Comment by cyberhck** [comment]
it might be okay, as stisla is supposed to be used as UI components, and if they want to add nicer scrollbar they can decide to go native or use library based on their requirements, since edge went with new chromium core now, it'll get better, safari is the worst browser we will have to support,

**Comment by tomferreira** [comment]
> Ok, can you send me a screenshot?

Current Edge
current-edge

New Edge (based on Chromium)
new-edge

**Comment by nauvalazhar** [comment]
Looks nice. But, don't know whether people will like the scroll view as seen in the Edge browser.

**Comment by nauvalazhar** [comment]
> > Ok, can you send me a screenshot?
> 
> Current Edge
> current-edge
> 
> New Edge (based on Chromium)
> new-edge

@polynar @cyberhck

**Comment by muhammaddicky** [comment]
Maybe it's better use class that contain scrollbars property instead set manual every components class that need scrollbars

**Comment by nauvalazhar** [comment]
I think it's better to be replaced with NiceScroll alternatives, such as Simplebar, Perfect Scrollbar or others, rather than using the native scrollbar.

**Comment by muhammaddicky** [comment]
> I think it's better to be replaced with NiceScroll alternatives, such as Simplebar, Perfect Scrollbar or others, rather than using the native scrollbar.

Yeah, because there is still a browser support issue for native scrollbar. Even project that i working on used to be using native scroll but because this issue i rather use plugin.

**Comment by nauvalazhar** [comment]
We can discuss about Nicescroll replacement [here](#13)

**Pull request closed without merging**
