### PR TITLE
add RTL mode

### PR DESCRIPTION
**Pull request by khanzadimahdi**
hi my bro. 
i have added RTL support into stisla. please merge the changes.
tnx

### CODE REVIEW

**Comment by nauvalazhar** [comment]
Hi, thank you for your great contribution. I'll check and test it first.

**Comment by nauvalazhar** [comment]
I have tried it, can you give a guide to using the RTL mode that you created? Also, you don't do it on all pages, only 30 pages out of 81. But, the interface is cool :)

**Comment by khanzadimahdi** [comment]
what kind of guide? you mean `code commenting` or `how to use instructions` ?
i will translate all pages a few weeks later. please merge the current translations.

**Comment by nauvalazhar** [comment]
Yep, the "how to use instructions".

**Comment by khanzadimahdi** [comment]
ok i will add `How to use` a few days later and create a pull request again.
tnx for merging my codes bro.

**Comment by nauvalazhar** [comment]
Ok, I hope you can maintain RTL mode

**Comment by nauvalazhar** [comment]
@all-contributors please add @khanzadimahdi for code

**Pull request merged**
