### PR TITLE
Stisla compact

### PR DESCRIPTION
**Pull request by pudyasto**
Membuat tampilan stisla lebih compact supaya bisa berjalan di monitor resolusi rendah.

### CODE REVIEW

**Comment by nauvalazhar** [comment]
Hi, thank you for your contribution. Could you send me a screenshot?

**Comment by pudyasto** [comment]
Hi, I've client with small monitor and I try to make little change with side navigation bar more slim, and set margin in sub menu. You can see image below as compare :
Original file : 
Screenshot from 2019-09-15 09-15-41

Slim design : 
Screenshot from 2019-09-15 09-08-10

**Comment by nauvalazhar** [comment]
Thank you for sending me a screenshot. One question, will it change the size by default? Or need to add a certain class to make it "slim".

**Comment by cyberhck** [comment]
please be careful, there are changes to the existing values, not sure if the original styles are still there.

**Comment by nauvalazhar** [comment]
> please be careful, there are changes to the existing values, not sure if the original styles are still there.

That's why I'm asked about class 😄
I'll merge this PR if there was a specific class to make layout "slim".

**Comment by pudyasto** [comment]
> > please be careful, there are changes to the existing values, not sure if the original styles are still there.
> 
> That's why I'm asked about class 
> I'll merge this PR if there was a specific class to make layout "slim".

Hehehe..... how about create new branch, or specific class is better solution.

**Comment by nauvalazhar** [comment]
Yes, I mean this will helpful for low-resolution. You must create additional classes for this, such as `layout-slim`, `slim-layout` or others.

**Comment by pudyasto** [comment]
Okay, I'll try to create new class for low-resolution mode.

**Pull request closed without merging**
